name: Upload Python Package to PyPI When a Tag is Pushed

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel

      - name: Build package
        run: |
          python -m build --sdist --wheel --no-isolation # python setup.py sdist bdist_wheel

      - name: Upload all the dists as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          compression-level: 0
          overwrite: true

  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/rokugu
    permissions:
      id-token: write
    needs: build
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
